/* Chapter 6 — Probability and Distributions */
(function () {
  MML.chapters.push({
    id: 'ch6', num: 6, icon: '🎲',
    title: 'Probability and Distributions',
    tagline: 'The mathematics of uncertainty — Bayes, Gaussians, and information. Every ML loss and every generative model speaks this language.',
    why: String.raw`Data is noisy, models are uncertain, predictions have error bars. Probability is the language built for exactly this. It gives ML its losses (log-likelihood, cross-entropy), its uncertainty quantification (posteriors), its most important distribution (the Gaussian — the noise model of the universe), and its inference engine (Bayes' rule). The book you are following devotes its longest chapter to this, and rightly: Chapters 8–12 all begin "assume the data was generated by…", and finishing that sentence requires everything here.`,
    goals: [
      String.raw`Manipulate conditional probabilities and apply Bayes' theorem without hesitation.`,
      String.raw`Compute means, variances, and covariance matrices from raw data.`,
      String.raw`Work with the multivariate Gaussian: marginals, conditionals, and linear transformations.`,
      String.raw`Connect information theory to ML losses: entropy, cross-entropy, KL divergence.`
    ],
    widget: null,
    concepts: [
      {
        id: 'c1',
        title: 'Probability spaces, conditioning, independence',
        subtitle: 'the rules of the game',
        intuition: String.raw`A probability space is a formal bet: you list everything that can happen (the <b>sample space</b>), assign a number in \([0,1]\) to each region of interest (the <b>events</b>), and the numbers must obey three common-sense axioms: nothing is below 0, the total is exactly 1, and disjoint possibilities add. <b>Conditional probability</b> is updating: given that you know event \(B\) happened, you shrink the universe to \(B\) and re-measure. <b>Independence</b> is the special case where the update changes nothing.`,
        math: [
          { h: 'Axioms (Kolmogorov)', t: String.raw`$$P(A) \ge 0, \qquad P(\Omega) = 1, \qquad P\!\left(\bigcup_i A_i\right) = \sum_i P(A_i) \;\; \text{for disjoint } A_i$$` },
          { h: 'Conditional probability', t: String.raw`$$P(A \mid B) = \frac{P(A \cap B)}{P(B)} \qquad (P(B) \gt 0)$$ Chain rule: \(P(A, B) = P(A \mid B)\,P(B)\), extended to any number of events.` },
          { h: 'Independence', t: String.raw`$$A, B \text{ independent} \iff P(A \cap B) = P(A)\,P(B)$$ Beware: <b>disjoint ≠ independent</b>. Disjoint events cannot co-occur (maximally dependent!); independent events do not influence each other's probabilities.` }
        ],
        ml: String.raw`Every generative model is a factorization of joint probabilities via the chain rule: an autoregressive language model computes \(P(w_1, \dots, w_T) = \prod_t P(w_t \mid w_{\lt t})\) — the chain rule of probability, learned by a transformer. Independence assumptions (naive Bayes) make hard problems tractable; knowing when independence <em>fails</em> (correlated features, leakage) is a core ML skill.`,
        byhand: {
          problem: String.raw`Two fair dice. (a) What is \(P(\text{sum} = 7)\)? (b) Given that the first die shows an even number, what is \(P(\text{sum} = 7)\)?`,
          steps: [
            { t: '(a) Count the favorable outcomes', d: String.raw`36 equally likely pairs. Sum \(= 7\): \((1,6), (2,5), (3,4), (4,3), (5,2), (6,1)\) — 6 outcomes ⟹ \(P = 6/36 = \tfrac16\).` },
            { t: '(b) Condition: first die even', d: String.raw`The conditioning shrinks the sample space to the \(18\) pairs with even first die. Of those, sum \(= 7\): \((2,5), (4,3), (6,1)\) — 3 outcomes. $$P(\text{sum}=7 \mid \text{first even}) = \tfrac{3}{18} = \tfrac16$$` },
            { t: 'Interpret', d: String.raw`Same as before — the first die's parity carries no information about the sum: formalizing that "no information" claim is exactly what conditional probability is for.` }
          ],
          answer: String.raw`(a) \(1/6\); (b) also \(1/6\) — conditioning sometimes confirms independence rather than changing anything.`
        }
      },
      {
        id: 'c2',
        title: "Bayes' theorem: the inference engine",
        subtitle: 'prior + data → posterior',
        intuition: String.raw`Bayes' theorem is the arithmetic of learning from evidence. You start with a <b>prior</b> belief \(P(H)\) about a hypothesis, observe data \(D\), and update to the <b>posterior</b> \(P(H \mid D)\). The <b>likelihood</b> \(P(D \mid H)\) — how strongly the hypothesis predicts the data — does the updating. The famous counterintuitive result: for rare events, even a very accurate test leaves the probability surprisingly low, because the prior dominates. ML "inference" means exactly this update, with models in place of hypotheses.`,
        math: [
          { h: "Bayes' theorem", t: String.raw`$$P(H \mid D) = \frac{P(D \mid H)\, P(H)}{P(D)} = \frac{\overbrace{P(D\mid H)}^{\text{likelihood}}\,\overbrace{P(H)}^{\text{prior}}}{\underbrace{P(D)}_{\text{evidence}}}$$ Evidence expands (law of total probability): \(P(D) = \sum_k P(D \mid H_k) P(H_k)\).` },
          { h: 'In distribution language (ML uses this)', t: String.raw`$$\underbrace{p(\boldsymbol{\theta} \mid \mathcal{D})}_{\text{posterior over parameters}} = \frac{p(\mathcal{D} \mid \boldsymbol{\theta})\; p(\boldsymbol{\theta})}{\int p(\mathcal{D} \mid \boldsymbol{\theta}')\, p(\boldsymbol{\theta}')\, d\boldsymbol{\theta}'}$$ "Bayesian machine learning" = computing or approximating this object; MAP estimation keeps only its peak.` }
        ],
        ml: String.raw`Bayes is everywhere: spam filters (\(P(\text{spam} \mid \text{words})\)); medical diagnostics; posterior over neural-net weights (Bayesian deep learning); the posterior mean is the optimal estimator under squared loss; and half of modern research (variational inference, diffusion models, RLHF reward models) is approximate Bayesian inference in disguise.`,
        byhand: {
          problem: String.raw`A disease affects \(1\%\) of a population. A test detects it with probability \(99\%\) when present (sensitivity), and falsely flags healthy people \(5\%\) of the time (false-positive rate). A random person tests positive. What is \(P(\text{disease} \mid +)\)?`,
          steps: [
            { t: 'Name the ingredients', d: String.raw`Prior: \(P(D) = 0.01\), \(P(\lnot D) = 0.99\). Likelihoods: \(P(+ \mid D) = 0.99\), \(P(+ \mid \lnot D) = 0.05\).` },
            { t: 'Numerator: the true-positive path', d: String.raw`$$P(D)P(+ \mid D) = 0.01 \times 0.99 = 0.0099$$` },
            { t: 'Denominator: all ways to test positive', d: String.raw`$$P(+) = 0.0099 + 0.99 \times 0.05 = 0.0099 + 0.0495 = 0.0594$$ (the false positives from the huge healthy population swamp the true positives!)` },
            { t: 'Divide', d: String.raw`$$P(D \mid +) = \frac{0.0099}{0.0594} = \frac{1}{6} \approx 16.7\%$$` },
            { t: 'The intuition that makes it stick', d: String.raw`Out of 10,000 people: 100 sick (99 test +) and 9,900 healthy (495 test +). So about 1 in 6 positives is truly sick. The test is "99% accurate" yet a positive result is usually wrong — <em>base rates matter</em>.` }
          ],
          answer: String.raw`\(P(D \mid +) = \tfrac16 \approx 16.7\%\). Always run Bayes through concrete counts when intuition wobbles.`
        }
      },
      {
        id: 'c3',
        title: 'Random variables: mean, variance, covariance',
        subtitle: 'summarizing randomness with a few numbers',
        intuition: String.raw`A <b>random variable</b> is a number produced by a chance experiment — the height of a random person, the loss of a random minibatch. Its full distribution is rich, but ML lives on summaries. The <b>mean</b> \(\mathbb{E}[X]\) is the long-run average (the balance point of the distribution's shape). The <b>variance</b> is the average squared spread around the mean (risk, noise level). For pairs of variables, <b>covariance</b> measures how they wiggle <em>together</em> — and stacking all pairwise covariances of a random vector gives the <b>covariance matrix</b>, the single most important matrix in statistics.`,
        math: [
          { h: 'Expectation and variance', t: String.raw`$$\mathbb{E}[X] = \sum_x x\, p(x) \;\; (\text{or } \int x\, p(x)dx), \qquad \mathbb{V}[X] = \mathbb{E}\big[(X - \mathbb{E}X)^2\big] = \mathbb{E}[X^2] - (\mathbb{E}X)^2$$ Linearity: \(\mathbb{E}[aX + bY] = a\,\mathbb{E}X + b\,\mathbb{E}Y\) — always, no independence needed.` },
          { h: 'Covariance and correlation', t: String.raw`$$\operatorname{Cov}(X, Y) = \mathbb{E}\big[(X - \mu_X)(Y - \mu_Y)\big] = \mathbb{E}[XY] - \mu_X\mu_Y, \qquad \rho = \frac{\operatorname{Cov}(X,Y)}{\sigma_X\sigma_Y} \in [-1, 1]$$` },
          { h: 'The covariance matrix', t: String.raw`$$\boldsymbol{\Sigma} = \operatorname{Cov}(\boldsymbol{X}) = \mathbb{E}\big[(\boldsymbol{X} - \boldsymbol{\mu})(\boldsymbol{X} - \boldsymbol{\mu})^\top\big] \in \mathbb{R}^{d \times d}$$ Always symmetric positive <em>semi</em>definite (variances on the diagonal, covariances off it). Under affine maps: \(\operatorname{Cov}(\boldsymbol{A}\boldsymbol{X} + \boldsymbol{b}) = \boldsymbol{A}\boldsymbol{\Sigma}\boldsymbol{A}^\top\) — the identity behind Cholesky sampling (Ch 4) and whitening.` }
        ],
        ml: String.raw`The empirical covariance matrix of your data is the object PCA eigendecomposes (Ch 10). Batch normalization rescales activations to zero mean and unit variance. Loss variance across minibatches explains SGD noise (Ch 7). And \(\operatorname{Cov}(\boldsymbol{A}\boldsymbol{z}) = \boldsymbol{A}\boldsymbol{A}^\top\) is the "reparameterization trick" identity that makes VAEs trainable.`,
        byhand: {
          problem: String.raw`Dataset (2 coordinates per point): \((1,1), (2,3), (3,2)\). Compute the mean vector and the full covariance matrix (divide by \(n\)), then find the correlation between the two coordinates.`,
          steps: [
            { t: 'Mean', d: String.raw`$$\boldsymbol{\mu} = \left(\tfrac{1+2+3}{3},\; \tfrac{1+3+2}{3}\right)^\top = (2, 2)^\top$$` },
            { t: 'Deviations from the mean', d: String.raw`$$\tilde{\boldsymbol{x}}_1 = (-1,-1)^\top, \quad \tilde{\boldsymbol{x}}_2 = (0,1)^\top, \quad \tilde{\boldsymbol{x}}_3 = (1,0)^\top$$` },
            { t: 'Average outer products', d: String.raw`$$\boldsymbol{\Sigma} = \frac{1}{3}\sum_i \tilde{\boldsymbol{x}}_i\tilde{\boldsymbol{x}}_i^\top = \frac{1}{3}\left[\begin{pmatrix} 1 & 1 \\ 1 & 1 \end{pmatrix} + \begin{pmatrix} 0 & 0 \\ 0 & 1 \end{pmatrix} + \begin{pmatrix} 1 & 0 \\ 0 & 0 \end{pmatrix}\right] = \begin{pmatrix} 2/3 & 1/3 \\ 1/3 & 2/3 \end{pmatrix}$$` },
            { t: 'Correlation', d: String.raw`$$\rho = \frac{\Sigma_{12}}{\sqrt{\Sigma_{11}\Sigma_{22}}} = \frac{1/3}{2/3} = \frac12$$ Mildly positive: points drift up-right together, but far from perfectly.` }
          ],
          answer: String.raw`\(\boldsymbol{\mu} = (2,2)^\top\), \(\boldsymbol{\Sigma} = \begin{pmatrix} 2/3 & 1/3 \\ 1/3 & 2/3 \end{pmatrix}\), \(\rho = 0.5\). (In Chapter 10 you will PCA this exact matrix and find its principal direction is \((1,1)/\sqrt2\).)`
        }
      },
      {
        id: 'c4',
        title: 'The Gaussian distribution',
        subtitle: 'univariate, multivariate, and its magical conditionals',
        intuition: String.raw`The Gaussian ("normal", bell curve) is what you get when <b>many small independent nudges add up</b> — that is the central limit theorem, and it is why heights, measurement errors, and averaged losses all look Gaussian. Its formula has exactly two knobs: a mean (where the center sits) and a variance (how wide). In many dimensions the covariance matrix \(\boldsymbol{\Sigma}\) takes over the "width" role — it stretches and rotates the bell. The Gaussian's superpowers: closed-form marginals and conditionals (conditioning never leaves the Gaussian family), and closure under linear maps — which is why it is the default noise model in ML.`,
        math: [
          { h: 'Univariate', t: String.raw`$$p(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\!\left(-\frac{(x - \mu)^2}{2\sigma^2}\right)$$ The \(\exp(-z^2/2)\) shape: quadratic penalty on distance from the mean, normalized to integrate to 1.` },
          { h: 'Multivariate', t: String.raw`$$\mathcal{N}(\boldsymbol{x} \mid \boldsymbol{\mu}, \boldsymbol{\Sigma}) = \frac{1}{\sqrt{(2\pi)^d \det\boldsymbol{\Sigma}}}\exp\!\left(-\tfrac12 (\boldsymbol{x} - \boldsymbol{\mu})^\top\boldsymbol{\Sigma}^{-1}(\boldsymbol{x} - \boldsymbol{\mu})\right)$$ The quadratic form in the exponent is the <b>Mahalanobis distance</b> — Euclidean distance re-weighted by the covariance (via Cholesky: \(\boldsymbol{\Sigma}^{-1} = \boldsymbol{L}^{-\top}\boldsymbol{L}^{-1}\)).` },
          { h: 'Marginals and conditionals (the magic)', t: String.raw`For a joint Gaussian, any sub-vector is Gaussian with the corresponding block of \(\boldsymbol{\mu}, \boldsymbol{\Sigma}\) (marginalize by just reading blocks!), and $$\mathbb{E}[\boldsymbol{x}_B \mid \boldsymbol{x}_A] = \boldsymbol{\mu}_B + \boldsymbol{\Sigma}_{BA}\boldsymbol{\Sigma}_{AA}^{-1}(\boldsymbol{x}_A - \boldsymbol{\mu}_A), \qquad \operatorname{Cov}[\boldsymbol{x}_B \mid \boldsymbol{x}_A] = \boldsymbol{\Sigma}_{BB} - \boldsymbol{\Sigma}_{BA}\boldsymbol{\Sigma}_{AA}^{-1}\boldsymbol{\Sigma}_{AB}$$ Linear regression with Gaussian noise is <em>exactly</em> the first of these lines — see Ch 9.` }
        ],
        ml: String.raw`Gaussian noise assumptions → least squares (Ch 9). \(\mathcal{N}(\boldsymbol{0}, \sigma^2\boldsymbol{I})\) latent noise + decoder → probabilistic PCA and VAEs (Ch 10). Denoising diffusion models learn to reverse Gaussian noise — their training loss is a weighted denoising regression. Gaussian processes place a Gaussian over <em>functions</em>. KL divergences between Gaussians regularize VAEs. When in doubt, ML reaches for a Gaussian.`,
        byhand: {
          problem: String.raw`Let \((X_1, X_2) \sim \mathcal{N}(\boldsymbol{0}, \boldsymbol{\Sigma})\) with \(\boldsymbol{\Sigma} = \begin{pmatrix} 1 & 0.8 \\ 0.8 & 1 \end{pmatrix}\) (correlation \(\rho = 0.8\)). Find the distribution of \(X_2\) given \(X_1 = 1\), and compare its spread with the marginal of \(X_2\).`,
          steps: [
            { t: 'Conditional mean', d: String.raw`$$\mathbb{E}[X_2 \mid X_1 = 1] = 0 + \boldsymbol{\Sigma}_{21}\boldsymbol{\Sigma}_{11}^{-1}(1 - 0) = \frac{0.8}{1}\cdot 1 = 0.8$$ Knowing \(X_1 = 1\) (one sd above its mean) drags the predicted \(X_2\) up by \(\rho\) sd's.` },
            { t: 'Conditional variance', d: String.raw`$$\mathbb{V}[X_2 \mid X_1] = \Sigma_{22} - \frac{\Sigma_{21}^2}{\Sigma_{11}} = 1 - 0.64 = 0.36 \quad (\sigma = 0.6)$$` },
            { t: 'Conclusion', d: String.raw`$$X_2 \mid X_1 = 1 \;\sim\; \mathcal{N}(0.8,\; 0.36)$$ Uncertainty shrank from \(\sigma = 1\) to \(0.6\): information about \(X_1\) explains a fraction \(0.8^2 = 64\%\) of \(X_2\)'s variance — \(R^2\) for Gaussians.` },
            { t: 'Limit cases', d: String.raw`\(\rho = 0\): conditional \(= \mathcal{N}(0,1)\), no information gained. \(\rho \to 1\): variance \(\to 0\), \(X_2\) becomes deterministic given \(X_1\). Correlation = predictability.` }
          ],
          answer: String.raw`\(X_2 \mid X_1{=}1 \sim \mathcal{N}(0.8,\, 0.36)\). Gaussian conditioning = a linear rule for the mean + a variance shrinkage by \(\rho^2\).`
        }
      },
      {
        id: 'c5',
        title: 'Fitting distributions: likelihood, MLE, and conjugate priors',
        subtitle: 'from Bayes to trainable parameters',
        intuition: String.raw`Given data and a family of distributions, which member fits best? The <b>likelihood</b> scores each candidate by the probability it assigns to the data actually observed; <b>maximum likelihood estimation</b> (MLE) picks the argmax. With a prior in the game, Bayes upgrades this to the <b>posterior</b>, and MAP estimation maximizes likelihood × prior. In the friendliest families (<b>conjugate</b> pairs like Beta–Bernoulli, Gaussian–Gaussian), the posterior stays in the same family and the update is literally "add counts" — the historical seed of all of Bayesian ML.`,
        math: [
          { h: 'Likelihood and MLE', t: String.raw`$$p(\mathcal{D} \mid \boldsymbol{\theta}) = \prod_i p(x_i \mid \boldsymbol{\theta}) \qquad \boldsymbol{\theta}^{\text{MLE}} = \arg\max_{\boldsymbol{\theta}} \; \sum_i \log p(x_i \mid \boldsymbol{\theta})$$ Logs turn products into sums (and prevent numerical underflow) — the log-likelihood is the quantity actually optimized.` },
          { h: 'Beta–Bernoulli conjugacy', t: String.raw`Prior \(\text{Beta}(\alpha, \beta)\), data: \(m\) heads in \(n\) flips: $$\text{Beta}(\alpha, \beta) \;+\; \text{data} \;\Longrightarrow\; \text{Beta}(\alpha + m,\; \beta + n - m)$$ Posterior mean \(\frac{\alpha + m}{\alpha + \beta + n}\): prior pseudo-counts literally mix with real counts.` },
          { h: 'MAP', t: String.raw`$$\boldsymbol{\theta}^{\text{MAP}} = \arg\max_{\boldsymbol{\theta}} \big[\log p(\mathcal{D} \mid \boldsymbol{\theta}) + \log p(\boldsymbol{\theta})\big]$$ A Gaussian prior on parameters ⟺ \(\ell_2\) regularization (ridge, Ch 9); a Laplace prior ⟺ \(\ell_1\). Regularization is a prior in disguise.` }
        ],
        ml: String.raw`Classification networks are trained by maximizing log-likelihood (minimizing cross-entropy) — MLE in disguise. "Generative models" are explicit density models \(p_{\boldsymbol{\theta}}(\boldsymbol{x})\) trained by MLE. VAEs and diffusion models maximize (bounds on) likelihood. Bayesian neural nets keep the full posterior; everything else uses MAP or MLE. Exponential families underlie generalized linear models and natural-gradient methods.`,
        byhand: {
          problem: String.raw`A coin lands heads 3 times in 5 flips. (a) Find the MLE of \(p = P(\text{heads})\). (b) Using prior \(p \sim \text{Beta}(2, 2)\), find the posterior, its mean, and the MAP estimate.`,
          steps: [
            { t: '(a) Likelihood and its maximum', d: String.raw`$$L(p) = p^3 (1-p)^2, \qquad \ell(p) = 3\log p + 2\log(1-p)$$ $$\ell'(p) = \frac{3}{p} - \frac{2}{1-p} = 0 \Rightarrow 3(1-p) = 2p \Rightarrow p = \frac35$$ MLE = observed frequency, \(0.6\).` },
            { t: '(b) Posterior by conjugacy', d: String.raw`Prior \(\text{Beta}(2,2)\) + data (\(m = 3\) heads, \(n - m = 2\) tails): $$\text{Beta}(2 + 3,\; 2 + 2) = \text{Beta}(5, 4)$$` },
            { t: 'Posterior mean and MAP', d: String.raw`Mean: \(\frac{5}{5+4} = \frac59 \approx 0.556\). MAP (mode): \(\frac{\alpha - 1}{\alpha + \beta - 2} = \frac{4}{7} \approx 0.571\).` },
            { t: 'Read the shrinkage', d: String.raw`Prior pulls estimates from the raw frequency \(0.6\) toward the prior mean \(0.5\): mean \(0.556\), MAP \(0.571\), both below \(0.6\). With little data, priors matter; with lots, likelihood wins — "data overwhelms the prior".` }
          ],
          answer: String.raw`MLE \(= 0.6\); posterior \(\text{Beta}(5,4)\) with mean \(\approx 0.556\) and MAP \(\approx 0.571\). Conjugacy makes Bayes arithmetic: add counts, read off answers.`
        }
      },
      {
        id: 'c6',
        title: 'Information theory: entropy, cross-entropy, KL',
        subtitle: 'why the ML loss function is what it is',
        intuition: String.raw`<b>Entropy</b> measures the surprise of a random variable: how many yes/no questions you need on average to pin down its value. A fair coin: 1 bit. A coin that lands heads 99% of the time: almost no surprise (you already expect heads). <b>Cross-entropy</b> measures the surprise of using the <em>wrong</em> distribution \(Q\) to encode data from \(P\) — and minimizing it forces \(Q\) toward \(P\). That is why "cross-entropy loss" is THE training loss of classifiers and language models: it is the most direct way to say "make your predicted distribution match the data". <b>KL divergence</b> is the extra surprise caused by using \(Q\) instead of \(P\) — the field's universal "distance" between distributions.`,
        math: [
          { h: 'Entropy', t: String.raw`$$H(P) = -\sum_x p(x) \log_b p(x) \qquad (b = 2: \text{bits})$$ Maximal for the uniform distribution; zero for a deterministic outcome.` },
          { h: 'Cross-entropy and KL', t: String.raw`$$H(P, Q) = -\sum_x p(x)\log q(x), \qquad \mathrm{KL}(P \| Q) = \sum_x p(x) \log\frac{p(x)}{q(x)} = H(P, Q) - H(P)$$ Gibbs' inequality: \(\mathrm{KL}(P\|Q) \ge 0\), with equality iff \(P = Q\) — but it is <b>not</b> symmetric (a divergence, not a distance).` },
          { h: 'Connection to likelihood', t: String.raw`$$\mathrm{KL}\big(p_{\text{data}} \,\|\, p_{\boldsymbol{\theta}}\big) = \underbrace{-\,\mathbb{E}_{\text{data}}[\log p_{\boldsymbol{\theta}}(\boldsymbol{x})]}_{-\text{expected log-likelihood}} + \text{const}$$ Minimizing KL ⟺ maximizing log-likelihood: "fitting a model" and "matching distributions" are the same task.` }
        ],
        ml: String.raw`Classification trains with cross-entropy between one-hot labels and softmax outputs; language models do the same over next-token distributions. VAEs minimize \(\mathrm{KL}(q\|p)\) in the ELBO; policy-gradient RL penalizes policy KL for stability; distillation transfers a teacher's distribution via KL. When a paper says "we minimize the reverse KL" vs "forward KL", which divergence you choose changes mode-seeking vs covering behavior — a genuinely research-level distinction that starts here.`,
        byhand: {
          problem: String.raw`(a) Compute the entropy of a fair coin and of a coin with \(P(\text{heads}) = 0.9\) (in bits, \(\log_2\)). (b) Compute \(\mathrm{KL}(\mathcal{N}(0,1) \,\|\, \mathcal{N}(1,1))\) using the formula \(\mathrm{KL} = \tfrac12\big[\frac{\sigma^2}{\sigma'^2} + \frac{(\mu' - \mu)^2}{\sigma'^2} - 1 + \ln\frac{\sigma'^2}{\sigma^2}\big]\).`,
          steps: [
            { t: '(a) Fair coin', d: String.raw`$$H = -\tfrac12\log_2\tfrac12 - \tfrac12\log_2\tfrac12 = 1 \text{ bit}$$ Maximum possible for two outcomes: you are maximally unsure.` },
            { t: '(a) Biased coin (0.9 / 0.1)', d: String.raw`$$H = -0.9\log_2 0.9 - 0.1\log_2 0.1 \approx 0.1368 + 0.3322 = 0.469 \text{ bits}$$ Less surprise: most flips are predictable heads.` },
            { t: '(b) Plug into the Gaussian KL formula', d: String.raw`\(\mu = 0, \mu' = 1, \sigma = \sigma' = 1\): $$\mathrm{KL} = \tfrac12\left[1 + \frac{(1-0)^2}{1} - 1 + \ln 1\right] = \tfrac12\left[1 + 1 - 1 + 0\right] = \tfrac12$$` },
            { t: 'Sanity of the reading', d: String.raw`The two bells overlap heavily (means differ by one sd), so the divergence is small — \(0.5\) nats. Shift the mean by 10 sd's and it explodes to \(50\): KL punishes disagreement quadratically for Gaussians.` }
          ],
          answer: String.raw`\(H(\text{fair}) = 1\) bit; \(H(0.9\text{-coin}) \approx 0.469\) bits; \(\mathrm{KL}(\mathcal{N}(0,1)\|\mathcal{N}(1,1)) = 0.5\). Cross-entropy training = closing the KL gap between model and data.`
        }
      }
    ],
    cheatsheet: [
      { n: "Bayes' theorem", t: String.raw`$$P(H \mid D) = \frac{P(D\mid H)P(H)}{P(D)}$$` },
      { n: 'Mean / variance', t: String.raw`$$\mathbb{E}[X] = \textstyle\sum x\, p(x), \qquad \mathbb{V}[X] = \mathbb{E}[X^2] - \mathbb{E}[X]^2$$` },
      { n: 'Covariance matrix', t: String.raw`$$\operatorname{Cov}(\boldsymbol{X}) = \mathbb{E}\big[(\boldsymbol{X}-\boldsymbol{\mu})(\boldsymbol{X}-\boldsymbol{\mu})^\top\big]$$` },
      { n: 'Gaussian', t: String.raw`$$\mathcal{N}(\boldsymbol{x}\mid \boldsymbol{\mu}, \boldsymbol{\Sigma}) = \frac{1}{\sqrt{(2\pi)^d \det\boldsymbol{\Sigma}}} \exp\!\big(-\tfrac12 (\boldsymbol{x}-\boldsymbol{\mu})^\top\boldsymbol{\Sigma}^{-1}(\boldsymbol{x}-\boldsymbol{\mu})\big)$$` },
      { n: 'Conditionals & marginals', t: String.raw`$$p(\boldsymbol{x}) = \int p(\boldsymbol{x}, \boldsymbol{y})\,d\boldsymbol{y}, \qquad p(\boldsymbol{y}\mid\boldsymbol{x}) = \frac{p(\boldsymbol{x}, \boldsymbol{y})}{p(\boldsymbol{x})}$$` },
      { n: 'Entropy / KL', t: String.raw`$$H(P) = -\textstyle\sum p \log p, \qquad \mathrm{KL}(P\|Q) = \textstyle\sum p \log\frac{p}{q} \ge 0$$` }
    ],
    practice: [
      {
        q: String.raw`A factory: machine \(A\) makes \(60\%\) of items with a \(2\%\) defect rate; machine \(B\) makes \(40\%\) with \(5\%\) defects. An item is defective. What is the probability it came from \(B\)?`,
        diff: 'easy',
        s: [
          String.raw`\(P(\text{def}, B) = 0.4 \times 0.05 = 0.02\); \(P(\text{def}, A) = 0.6 \times 0.02 = 0.012\).`,
          String.raw`\(P(\text{def}) = 0.032\).`,
          String.raw`\(P(B \mid \text{def}) = 0.02/0.032 = \tfrac58 = 0.625\).`
        ],
        fin: String.raw`\(62.5\%\). Despite making fewer items, \(B\)'s higher defect rate dominates the posterior.`
      },
      {
        q: String.raw`For a fair coin flipped 3 times: compute \(\mathbb{E}[X]\) and \(\mathbb{V}[X]\) where \(X\) = number of heads, using the definitions. Then verify with the Bernoulli-sum shortcut \(\mathbb{V} = np(1-p)\).`,
        diff: 'easy',
        s: [
          String.raw`\(\mathbb{E}[X] = 0\cdot\tfrac18 + 1\cdot\tfrac38 + 2\cdot\tfrac38 + 3\cdot\tfrac18 = 1.5 = np\) ✓.`,
          String.raw`\(\mathbb{E}[X^2] = 0 + 1\cdot\tfrac38 + 4\cdot\tfrac38 + 9\cdot\tfrac18 = \tfrac{24}{8} = 3\).`,
          String.raw`\(\mathbb{V}[X] = 3 - 1.5^2 = 0.75\); shortcut: \(3 \cdot \tfrac12 \cdot \tfrac12 = 0.75\) ✓.`
        ],
        fin: String.raw`\(\mathbb{E}[X] = 1.5\), \(\mathbb{V}[X] = 0.75\).`
      },
      {
        q: String.raw`Compute the covariance matrix of the dataset \(\{(1,1), (2,3), (3,2)\}\) (coordinates \(x_1, x_2\)) and its eigenvalues. (Keep this one — Chapter 10 runs PCA on exactly this data.)`,
        diff: 'med',
        s: [
          String.raw`Mean: \(\boldsymbol{\mu} = (2, 2)^\top\). Deviations: \((-1,-1), (0,1), (1,0)\).`,
          String.raw`Entries (divide by \(n = 3\)): \(\Sigma_{11} = (1+0+1)/3 = \tfrac23\); \(\Sigma_{22} = (1+1+0)/3 = \tfrac23\); \(\Sigma_{12} = ((-1)(-1) + 0 + 0)/3 = \tfrac13\).`,
          String.raw`$$\boldsymbol{\Sigma} = \begin{pmatrix} 2/3 & 1/3 \\ 1/3 & 2/3 \end{pmatrix}, \qquad \lambda^2 - \tfrac43\lambda + \tfrac13 = 0 \Rightarrow \lambda = 1, \tfrac13$$`
        ],
        fin: String.raw`\(\boldsymbol{\Sigma} = \begin{pmatrix} 2/3 & 1/3 \\ 1/3 & 2/3\end{pmatrix}\), eigenvalues \(1\) and \(1/3\): more variance along the \((1,1)\) direction — the seed of PCA.`
      },
      {
        q: String.raw`For \(\boldsymbol{X} \sim \mathcal{N}(\boldsymbol{0}, \boldsymbol{\Sigma})\) with \(\boldsymbol{\Sigma} = \begin{pmatrix} 1 & 0.8 \\ 0.8 & 1 \end{pmatrix}\): compute \(\mathbb{E}[X_2 \mid X_1 = 1]\) and \(\mathbb{V}[X_2 \mid X_1 = 1]\). Interpret the result for \(\rho = 0\).`,
        diff: 'med',
        s: [
          String.raw`Conditioning formula: \(\mathbb{E}[X_2 \mid X_1 = x] = \mu_2 + \frac{\Sigma_{21}}{\Sigma_{11}}(x - \mu_1) = 0.8\,x\) here.`,
          String.raw`\(\mathbb{V}[X_2 \mid X_1] = \Sigma_{22} - \frac{\Sigma_{21}^2}{\Sigma_{11}} = 1 - 0.64 = 0.36\) (sd \(0.6\)).`,
          String.raw`If \(\rho = 0\): mean \(0\), variance \(1\) — knowing \(X_1\) tells you nothing about \(X_2\) exactly when the variables are uncorrelated.`
        ],
        fin: String.raw`\(\mathbb{E}[X_2 \mid X_1 = 1] = 0.8\), \(\mathbb{V} = 0.36\). For Gaussians, zero covariance = true independence — special to Gaussians and hugely convenient.`
      },
      {
        q: String.raw`(Proof) Prove \(\mathbb{V}[X] = \mathbb{E}[X^2] - \mathbb{E}[X]^2\) from the definition \(\mathbb{V}[X] = \mathbb{E}[(X - \mu)^2]\).`,
        diff: 'hard',
        s: [
          String.raw`Expand the square: \(\mathbb{E}[(X-\mu)^2] = \mathbb{E}[X^2 - 2\mu X + \mu^2]\).`,
          String.raw`Linearity of expectation (a constant passes through): \(= \mathbb{E}[X^2] - 2\mu\,\mathbb{E}[X] + \mu^2\).`,
          String.raw`Substitute \(\mu = \mathbb{E}[X]\): \(= \mathbb{E}[X^2] - 2\mu^2 + \mu^2 = \mathbb{E}[X^2] - \mu^2\). ∎`
        ],
        fin: String.raw`Three lines, using only linearity of \(\mathbb{E}\). This identity is why "second moment minus mean squared" appears in every variance computation.`
      }
    ]
  });
})();
