/* Chapter 11 — Density Estimation with Gaussian Mixture Models */
(function () {
  MML.chapters.push({
    id: 'ch11', num: 11, icon: '👥',
    title: 'Density Estimation with Gaussian Mixtures',
    tagline: 'Clustering as density modeling: latent variables, soft assignments, and the EM algorithm — expectation and maximization in a loop.',
    why: String.raw`Not every dataset wants a line through it. Often the data is <b>clusters</b>: groups of points, each group blob-shaped, no labels provided. The Gaussian mixture model says: the data is generated by first choosing a cluster (a hidden choice), then sampling a point from that cluster's Gaussian. The hidden choice — a <b>latent variable</b> — is what makes fitting hard and interesting, and the <b>EM algorithm</b> is the classical solution: guess the hidden assignments (E), refit the clusters given the guesses (M), repeat. EM is one of the most reused algorithms in statistics and ML — it also trains the missing-data models behind recommender systems and the E-step inside variational inference.`,
    goals: [
      String.raw`Write down the GMM density and the role of the latent cluster variable.`,
      String.raw`Compute responsibilities (E-step) by hand.`,
      String.raw`Derive and apply the M-step updates for \(\mu, \sigma^2, \pi\).`,
      String.raw`Explain why EM monotonically improves the likelihood — and when it fails (local optima).`
    ],
    widget: 'gmm',
    concepts: [
      {
        id: 'c1',
        title: 'The mixture model and its hidden variable',
        subtitle: 'a Gaussian you cannot see, choosing which blob you land in',
        intuition: String.raw`A single Gaussian models one blob. Many datasets (two humps in a histogram) need several. The mixture story: flip a \(K\)-sided hidden coin (choose cluster \(z\), with probabilities \(\pi_1, \dots, \pi_K\)), then sample from cluster \(z\)'s Gaussian. You <b>never observe \(z\)</b> — that is what "latent" means — so each data point sits under a blend of all the Gaussians, and the blending weights \(\pi_k\) are learnable too. The whole model is still just a weighted sum of Chapter 6's Gaussians.`,
        math: [
          { h: 'Generative story and density', t: String.raw`$$z \sim \text{Cat}(\pi_1, \dots, \pi_K), \qquad \boldsymbol{x} \mid z = k \sim \mathcal{N}(\boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$$ $$p(\boldsymbol{x}) = \sum_{k=1}^{K} \pi_k\, \mathcal{N}(\boldsymbol{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k), \qquad \pi_k \ge 0, \quad \sum_k \pi_k = 1$$` },
          { h: 'Why fitting is not straightforward', t: String.raw`Log-likelihood: $$\log p(\mathcal{D}) = \sum_i \log\Big(\sum_k \pi_k \mathcal{N}(\boldsymbol{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)\Big)$$ The <b>sum inside the log</b> blocks the logarithm from reaching the parameters: derivatives entangle all clusters at once, and no closed-form MLE exists (unlike plain regression). This one algebraic inconvenience is the reason EM exists.` }
        ],
        ml: String.raw`GMMs are soft \(k\)-means (with learned cluster sizes and shapes), the classical density estimator for multimodal data, the speaker model in speech systems, and an anomaly detector (points in low-density regions are anomalies). Latent-variable thinking here scales up to topic models, HMMs, and VAEs.`,
        byhand: {
          problem: String.raw`A 2-component mixture on \(\mathbb{R}\): \(\pi_1 = 0.7\) at \(\mu_1 = 0\), \(\pi_2 = 0.3\) at \(\mu_2 = 3\), both \(\sigma^2 = 1\). Compute the density \(p(x)\) at \(x = 0\) and at \(x = 1.5\) (use \(\mathcal{N}(x;\mu,1) = \frac{1}{\sqrt{2\pi}}e^{-(x-\mu)^2/2} \approx 0.399\, e^{-(x-\mu)^2/2}\)).`,
          steps: [
            { t: 'At x = 0 (a cluster center)', d: String.raw`$$p(0) = 0.7 \times 0.399 + 0.3 \times 0.399\, e^{-4.5} = 0.2793 + 0.3 \times 0.00443 = 0.2806$$ Dominated by cluster 1 — as expected at its center.` },
            { t: 'At x = 1.5 (midway)', d: String.raw`Both components sit \(1.5\) away: \(e^{-1.125} = 0.3247\). $$p(1.5) = (0.7 + 0.3) \times 0.399 \times 0.3247 = 0.1296$$` },
            { t: 'Read the shape', d: String.raw`The midpoint is a valley: each point's density is a <em>blend</em>, and points between clusters pay both components' penalties. The mixture can express shapes (two humps, skew, heavy tails) no single Gaussian can.` }
          ],
          answer: String.raw`\(p(0) \approx 0.281\), \(p(1.5) \approx 0.130\). A mixture density is a weighted blend — the weights \(\pi_k\) are learned, not fixed.`
        }
      },
      {
        id: 'c2',
        title: 'The E-step: responsibilities',
        subtitle: 'Bayes assigns each point softly to every cluster',
        intuition: String.raw`Given current cluster parameters, ask for each point: <b>which cluster probably generated it?</b> Bayes' theorem answers, and the answer is soft: point \(x_i\) is 97% cluster 1, 3% cluster 2. These <b>responsibilities</b> \(r_{ik}\) are posterior probabilities \(p(z_i = k \mid x_i)\) — the model's current best guess of the hidden labels. Far points, near points, borderline points: each gets a fractional membership instead of a hard verdict. This softness is what lets the M-step refit clusters using <em>weighted</em> averages rather than all-or-nothing counts.`,
        math: [
          { h: 'Responsibility (posterior over the latent)', t: String.raw`$$r_{ik} = p(z_i = k \mid \boldsymbol{x}_i) = \frac{\pi_k\, \mathcal{N}(\boldsymbol{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)}{\sum_{j} \pi_j\, \mathcal{N}(\boldsymbol{x}_i \mid \boldsymbol{\mu}_j, \boldsymbol{\Sigma}_j)}, \qquad \sum_k r_{ik} = 1$$ Literally Bayes' theorem (Ch 6): likelihood × prior, normalized by the evidence.` },
          { h: 'Effective counts', t: String.raw`$$N_k = \sum_i r_{ik} \qquad \text{(soft count of cluster } k\text{, need not be an integer)}$$ \(N_k\) plays the role of "how much data cluster \(k\) owns" and drives every M-step update.` }
        ],
        ml: String.raw`Soft assignments are the GMM's advantage over \(k\)-means: borderline points influence <em>both</em> clusters proportionally, and uncertainty is explicit. The same posterior-over-latents computation appears as the E-step of every EM model and as the encoder of a VAE (amortized responsibilities).`,
        byhand: {
          problem: String.raw`With \(\pi_1 = \pi_2 = \tfrac12\), \(\sigma = 1\), \(\mu_1 = 1\), \(\mu_2 = 4\), compute the responsibilities of the point \(x = 2\). Which cluster owns it, and how confidently?`,
          steps: [
            { t: 'Unnormalized scores', d: String.raw`$$\pi_1\mathcal{N}(2; 1, 1) = \tfrac12 \times 0.399\, e^{-0.5} = 0.5 \times 0.242 = 0.121$$ $$\pi_2\mathcal{N}(2; 4, 1) = \tfrac12 \times 0.399\, e^{-2} = 0.5 \times 0.0540 = 0.0270$$` },
            { t: 'Normalize (Bayes)', d: String.raw`$$r_1 = \frac{0.121}{0.121 + 0.0270} = 0.818, \qquad r_2 = 0.182$$` },
            { t: 'Read it', d: String.raw`\(x = 2\) is 1 sd from cluster 1 but 2 sd from cluster 2 — an \(e^{1.5} \approx 4.5\times\) likelihood ratio, moderated by the equal priors. Confidence comes from the <em>ratio</em>; a point at \(x = 3.5\) would flip the verdict with the same rule.` }
          ],
          answer: String.raw`\(r = (0.818, 0.182)\): cluster 1 owns it softly. Responsibilities are just Bayes with Gaussians as likelihoods.`
        }
      },
      {
        id: 'c3',
        title: 'The M-step: refitting clusters from soft counts',
        subtitle: 'weighted means, weighted variances, learned priors',
        intuition: String.raw`Now pretend the responsibilities are the truth: cluster 1 owns \(N_1\) (fractional) data points, distributed as \(r_{i1}\). Refit each Gaussian to <b>its weighted data</b>: the mean is the responsibility-weighted average, the variance the weighted spread, and each mixing weight the cluster's share of total soft mass. Each update, taken alone, is just weighted least squares / weighted statistics — nothing exotic. The magic is only in the loop: new parameters change responsibilities, which change parameters… and the likelihood climbs every turn.`,
        math: [
          { h: 'The updates', t: String.raw`$$\boldsymbol{\mu}_k = \frac{1}{N_k}\sum_i r_{ik}\, \boldsymbol{x}_i, \qquad \boldsymbol{\Sigma}_k = \frac{1}{N_k}\sum_i r_{ik}(\boldsymbol{x}_i - \boldsymbol{\mu}_k)(\boldsymbol{x}_i - \boldsymbol{\mu}_k)^\top, \qquad \pi_k = \frac{N_k}{n}$$ Soft \(k\)-means: replace \(r_{ik} \in \{0,1\}\) by hard assignments and \(\boldsymbol{\Sigma}_k = \boldsymbol{I}\) — you recover \(k\)-means exactly.` },
          { h: 'Where these come from', t: String.raw`They maximize the <b>expected complete-data log-likelihood</b> $$Q(\boldsymbol{\theta}) = \sum_i\sum_k r_{ik}\big[\log \pi_k + \log \mathcal{N}(\boldsymbol{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)\big]$$ — treat \(r_{ik}\) as fixed (they were computed in the E-step); then the three parameter families decouple and each has a standard weighted-MLE solution (Lagrange multipliers give \(\pi_k = N_k/n\)).` }
        ],
        ml: String.raw`The E/M loop is a <b>coordinate ascent</b> prototype: alternate "infer hidden quantities" with "optimize parameters given them". The same two-beat rhythm drives \(k\)-means, the Baum–Welch algorithm for HMMs, missing-data imputation, and variational EM in VAEs. Once you see it here, you will recognize it everywhere.`,
        byhand: {
          problem: String.raw`Two points, responsibilities \(r_{i1} = (0.8, 0.2)\), points \(x_1 = 0, x_2 = 3\). For cluster 1: compute \(N_1\), the updated \(\mu_1\), and (with \(\sigma^2\)) the updated variance. Also update \(\pi_1\) for \(n = 2\) points.`,
          steps: [
            { t: 'Soft count', d: String.raw`$$N_1 = 0.8 + 0.2 = 1.0$$ (cluster 1 "owns" exactly one point, split across the two.)` },
            { t: 'Weighted mean', d: String.raw`$$\mu_1 = \frac{0.8 \times 0 + 0.2 \times 3}{1.0} = 0.6$$ Pulled toward \(x_2\) in proportion to its membership.` },
            { t: 'Weighted variance', d: String.raw`$$\sigma_1^2 = 0.8(0 - 0.6)^2 + 0.2(3 - 0.6)^2 = 0.8 \times 0.36 + 0.2 \times 5.76 = 0.288 + 1.152 = 1.44$$` },
            { t: 'Mixing weight', d: String.raw`$$\pi_1 = \frac{N_1}{n} = \frac{1}{2}$$ (and \(\pi_2 = 0.5\): with these responsibilities both clusters hold equal soft mass.)` }
          ],
          answer: String.raw`\(N_1 = 1\), \(\mu_1 = 0.6\), \(\sigma_1^2 = 1.44\), \(\pi_1 = 0.5\). Every GMM update is a weighted average — the E-step supplies the weights.`
        }
      },
      {
        id: 'c4',
        title: 'Why EM works — and when it doesn\u2019t',
        subtitle: 'monotone climbing, the ELBO, and local optima',
        intuition: String.raw`Two guarantees and one caveat. Guarantee 1: the log-likelihood <b>never decreases</b> across an EM iteration — each turn either improves it or leaves it unchanged. Guarantee 2: it converges to a stationary point of the likelihood. The caveat: <em>which</em> stationary point depends on the starting parameters — mixtures are multimodal, so EM can settle into a poor local optimum (or collapse a cluster onto a single point, a "singularity"). Practice therefore restarts EM from several random initializations and keeps the best. The proof of monotonicity introduces the <b>ELBO</b> — the same lower bound that powers variational inference in deep generative models.`,
        math: [
          { h: 'The monotonicity argument in one line', t: String.raw`Decompose, for any distribution \(q\) over latents: $$\log p(\mathcal{D} \mid \boldsymbol{\theta}) = \underbrace{\mathbb{E}_q[\log p(\mathcal{D}, \boldsymbol{z} \mid \boldsymbol{\theta})]}_{\text{ELBO}(q, \boldsymbol{\theta})} - \underbrace{\mathbb{E}_q\Big[\log \frac{q(\boldsymbol{z})}{p(\boldsymbol{z} \mid \mathcal{D}, \boldsymbol{\theta})}\Big]}_{\mathrm{KL}(q \,\|\, p(\boldsymbol{z}|\mathcal{D},\boldsymbol{\theta})) \;\ge\; 0}$$ E-step: set \(q = p(\boldsymbol{z} \mid \mathcal{D}, \boldsymbol{\theta}^{\text{old}})\), making \(\mathrm{KL} = 0\) and the ELBO <em>touch</em> the likelihood. M-step: raise the ELBO w.r.t. \(\boldsymbol{\theta}\). Likelihood = ELBO + KL: it can only rise.` },
          { h: 'Failure modes', t: String.raw`Local optima (bad init); <b>singularities</b>: a component collapsing onto one point sends its variance \(\to 0\) and likelihood \(\to \infty\) (no maximum exists!); label switching (components are interchangeable). Remedies: multiple restarts, variance floors, priors on parameters (MAP-EM), and smart initialization (e.g. \(k\)-means first).` }
        ],
        ml: String.raw`The ELBO on this card is <b>the</b> objective of variational autoencoders (minimize the KL, maximize the expected log-likelihood — the "reconstruction + KL" loss you may have seen). EM's coordinate-ascent view also explains Gibbs sampling and mean-field methods. If you continue to research, this card is the seed of an entire subfield: variational inference.`,
        byhand: {
          problem: String.raw`(Conceptual workout) On the dataset \(\{0, 1, 4, 5\}\) with two components initialized at \(\mu = 1, 4\), \(\sigma = 1\), \(\pi = \tfrac12\): after one EM step (worked fully in the practice set below) the parameters become \(\mu \approx 0.52, 4.48\), \(\sigma \approx 0.57\). Explain, without computing, why the likelihood must have increased.`,
          steps: [
            { t: 'Identify the two beats', d: String.raw`E-step: \(q\) set to the exact posterior at the old parameters ⟹ ELBO equals the old log-likelihood exactly (KL term = 0).` },
            { t: 'M-step improves Q', d: String.raw`The M-step <em>maximizes</em> \(Q\) (the expected complete log-likelihood) at \(q\) fixed: new \(\boldsymbol{\theta}\) has \(Q(\boldsymbol{\theta}^{\text{new}}) \ge Q(\boldsymbol{\theta}^{\text{old}})\).` },
            { t: 'Chain the inequalities', d: String.raw`$$\log p(\mathcal{D} \mid \boldsymbol{\theta}^{\text{new}}) \;\ge\; \text{ELBO}(q, \boldsymbol{\theta}^{\text{new}}) \;\ge\; \text{ELBO}(q, \boldsymbol{\theta}^{\text{old}}) \;=\; \log p(\mathcal{D} \mid \boldsymbol{\theta}^{\text{old}})$$ The new likelihood is at least the new ELBO, which is at least the old ELBO, which <em>equals</em> the old likelihood. Monotone climb, guaranteed — the numbers (\(-7.42 \to -5.74\)) merely comply.` }
          ],
          answer: String.raw`E makes the bound tight; M raises the bound; hence the likelihood rises. One decomposition, two easy inequalities — that is the whole proof.`
        }
      }
    ],
    cheatsheet: [
      { n: 'GMM density', t: String.raw`$$p(\boldsymbol{x}) = \sum_k \pi_k\, \mathcal{N}(\boldsymbol{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k), \qquad \sum_k \pi_k = 1$$` },
      { n: 'E-step', t: String.raw`$$r_{ik} = \frac{\pi_k \mathcal{N}(\boldsymbol{x}_i\mid\boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)}{\sum_j \pi_j \mathcal{N}(\boldsymbol{x}_i \mid \boldsymbol{\mu}_j, \boldsymbol{\Sigma}_j)}, \qquad N_k = \sum_i r_{ik}$$` },
      { n: 'M-step', t: String.raw`$$\boldsymbol{\mu}_k = \frac{\sum_i r_{ik}\boldsymbol{x}_i}{N_k}, \quad \boldsymbol{\Sigma}_k = \frac{\sum_i r_{ik}(\boldsymbol{x}_i - \boldsymbol{\mu}_k)(\boldsymbol{x}_i-\boldsymbol{\mu}_k)^\top}{N_k}, \quad \pi_k = \frac{N_k}{n}$$` },
      { n: 'Monotonicity', t: String.raw`$$\log p \;=\; \text{ELBO} + \mathrm{KL} \;\Rightarrow\; \text{each EM step never decreases } \log p$$` },
      { n: 'Caveats', t: String.raw`$$\text{local optima, singularities } (\sigma^2 \to 0), \text{ label switching} \;\Rightarrow\; \text{restarts + variance floors}$$` }
    ],
    practice: [
      {
        q: String.raw`One full EM iteration, by hand, on \(\mathcal{D} = \{0, 1, 4, 5\}\) with \(K = 2\), initialized at \(\mu_1 = 1, \mu_2 = 4\), \(\sigma_1 = \sigma_2 = 1\), \(\pi_1 = \pi_2 = \tfrac12\). Compute the E-step responsibilities and the M-step updates. (Use \(\mathcal{N}(x;\mu,1) \approx 0.399\,e^{-(x-\mu)^2/2}\).)`,
        diff: 'hard',
        s: [
          String.raw`**E-step.** Equal priors cancel. Unnormalized likelihoods: \(x = 0\): \(0.242\) vs \(0.00013\); \(x = 1\): \(0.399\) vs \(0.0044\); \(x = 4\): \(0.0044\) vs \(0.399\); \(x = 5\): \(0.00013\) vs \(0.242\).`,
          String.raw`Responsibilities \(r_{i1}\): \(\approx (0.999,\; 0.989,\; 0.011,\; 0.001)\). The outer points are owned almost surely; inner points less decisively.`,
          String.raw`**M-step, cluster 1.** \(N_1 = 0.999 + 0.989 + 0.011 + 0.001 \approx 2.0\). $$\mu_1 = \tfrac{1}{2}\big[0(0.999) + 1(0.989) + 4(0.011) + 5(0.001)\big] \approx \tfrac{1.036}{2} = 0.52$$`,
          String.raw`\(\sigma_1^2 = \tfrac{1}{2}\big[0.999(0.52)^2 + 0.989(0.48)^2 + 0.011(3.48)^2 + 0.001(4.48)^2\big] \approx 0.32\), \(\sigma_1 \approx 0.57\). By symmetry \(\mu_2 \approx 4.48\), \(\sigma_2 \approx 0.57\). \(\pi_1 = N_1/4 = 0.5\) (unchanged).`,
          String.raw`**Read the step.** Means moved outward (\(1 \to 0.52\), \(4 \to 4.48\)) and variances shrank (\(1 \to 0.57\)): the components specialized around \(\{0, 1\}\) and \(\{4, 5\}\). Iterate the widget above to watch convergence.`
        ],
        fin: String.raw`After one step: \(\mu \approx (0.52, 4.48)\), \(\sigma \approx 0.57\), \(\pi = (0.5, 0.5)\). Log-likelihood: \(-7.42 \to -5.74\) — up, as guaranteed.`
      },
      {
        q: String.raw`Using the updated parameters (\(\mu_1 = 0.52, \sigma_1 = 0.57\), \(\mu_2 = 4.48, \sigma_2 = 0.57\), \(\pi = \tfrac12\)), compute the mixture density at \(x = 2.5\) — the valley between clusters.`,
        diff: 'med',
        s: [
          String.raw`\(\mathcal{N}(2.5; 0.52, 0.57) = \tfrac{0.399}{0.57}e^{-\frac{(1.98)^2}{2 \times 0.3249}} \approx 0.70 \times e^{-6.03} \approx 0.0017\).`,
          String.raw`Same by symmetry for cluster 2: \(0.0017\).`,
          String.raw`\(p(2.5) = \tfrac12(0.0017) + \tfrac12(0.0017) = 0.0017\): a deep valley — the fitted model confidently says "nothing lives here".`
        ],
        fin: String.raw`\(\approx 0.0017\), versus \(\approx 0.13\) at the same point under the initial parameters: EM sharpened the separation decisively.`
      },
      {
        q: String.raw`Derive the M-step for \(\mu_k\): maximize \(Q(\mu_k) = \sum_i r_{ik}\log\mathcal{N}(x_i \mid \mu_k, \sigma^2)\) w.r.t. \(\mu_k\) (σ fixed) and confirm the weighted-mean formula.`,
        diff: 'hard',
        s: [
          String.raw`Expand the log-density: \(\log\mathcal{N}(x_i \mid \mu_k, \sigma^2) = -\tfrac{(x_i - \mu_k)^2}{2\sigma^2} + \text{const}\). So \(Q(\mu_k) = -\frac{1}{2\sigma^2}\sum_i r_{ik}(x_i - \mu_k)^2 + \text{const}\).`,
          String.raw`Derivative: \(\frac{\partial Q}{\partial \mu_k} = \frac{1}{\sigma^2}\sum_i r_{ik}(x_i - \mu_k) = 0 \Rightarrow \mu_k \sum_i r_{ik} = \sum_i r_{ik} x_i\).`,
          String.raw`Hence \(\mu_k = \frac{\sum_i r_{ik}x_i}{\sum_i r_{ik}} = \frac{\sum_i r_{ik}x_i}{N_k}\) — a weighted mean; \(Q\) is concave in \(\mu_k\), so this is the maximum. ∎`
        ],
        fin: String.raw`The M-step is weighted least squares in disguise: \(r_{ik}\) are the weights. All three GMM updates fall out of the same "expected complete-data log-likelihood".`
      },
      {
        q: String.raw`Explain, in at most 5 sentences, why GMM clustering with EM can produce a worse result than \(k\)-means on some datasets, and name two practical remedies.`,
        diff: 'med',
        s: [
          String.raw`EM maximizes a non-convex likelihood with many local optima: the result depends on initialization, so a bad start (two components planted inside one true cluster) can trap it.`,
          String.raw`It can also collapse a component onto a single data point (variance \(\to 0\), likelihood \(\to \infty\)) — a singularity with no finite maximum.`,
          String.raw`Remedies: (1) multiple random restarts / \(k\)-means initialization, keep the best likelihood; (2) variance floors or priors (MAP-EM) to prevent collapse. (Also: split-and-merge heuristics, smart component counts via BIC.)`
        ],
        fin: String.raw`Non-convexity + singularities are GMM's price for flexibility; restarts and regularization are the standard tolls.`
      }
    ]
  });
})();
